[workspace]
resolver = "3"
members = ["packages/*"]

[workspace.package]
rust-version = "1.85.0"
edition = "2024"
license = "Apache-2.0"
authors = ["NESP"]
repository = "https://github.com/nespjin/SpiderX"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[workspace.lints.clippy]
# Performance optimizations
unnecessary_clone = "warn"
too_many_arguments = "warn"

# Code quality
unwrap_used = "warn"
expect_used = "warn"

# Style improvements
manual_strip = "warn"
match_like_matches_macro = "warn"

[workspace.lints.rust]
# dead_code = "allow"
